GET http://localhost:4000/todos/?status=TO%20DO

###


GET http://localhost:4000/todos/?priority=HIGH

###

GET http://localhost:4000/todos/?priority=LOW&status=IN%20PROGRESS

###

GET http://localhost:4000/todos/?search_q=Play

###
GET http://localhost:4000/todos/2/

###
POST http://localhost:4000/todos/
Content-Type: application/json

{
    "id":10,
    "todo":"Finalize event theme",
    "priority":"LOW",
    "status":"TO DO"
}

###
PUT http://localhost:4000/todos/1/
Content-Type: application/json

{
    "status": "DONE"

}
###

PUT http://localhost:4000/todos/1/
Content-Type: application/json

{
    "priority": "HIGH"
}

###

PUT http://localhost:4000/todos/1/
Content-Type: application/json

{
    "todo": "Some task"
}

###

DELETE http://localhost:4000/todos/4/